"""
Legion SharedWorldModel
========================
The collective's persistent, shared memory. All nodes read and write here.
This is what makes Legion a hivemind rather than a debate system.

Replaces: AgentMemory (ephemeral, per-agent)
Extends:  memory.py (persistent, but single-user note storage)

Architecture:
    - Beliefs: things the collective has committed to as true
    - Goals:   what the collective wants to accomplish (feeds GoalStack)
    - Events:  append-only log of everything that happened
    - Nodes:   registry of active agents and their capabilities

Storage: JSON on disk (simple, inspectable, no dependencies)
Retrieval: Same recency+importance+relevance formula from AgentMemory,
           now operating across the shared pool instead of per-agent.

Thread-safe: asyncio.Lock protects all writes (debate_async.py is async).

Next files to build:
    - goal_stack.py   (reads/writes self.goals)
    - dispatcher.py   (reads self.beliefs, writes self.events)
    - consensus.py    (writes self.beliefs after node voting)
    - run_loop.py     (the autonomous heartbeat)
"""

import json
import re
import asyncio
import numpy as np
from datetime import datetime
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional


# ── Data structures ───────────────────────────────────────────────────────────

@dataclass
class Belief:
    """
    Something the collective has committed to as true.
    Written by ConsensusEngine after nodes reach agreement.
    """
    id:          str
    content:     str
    confidence:  float
    source:      str
    created_at:  str
    updated_at:  str
    tags:        list  = field(default_factory=list)
    evidence:    list  = field(default_factory=list)


@dataclass
class Goal:
    """
    Something the collective wants to accomplish.
    Can be seeded by a human or self-generated by a Planner node.
    """
    id:          str
    description: str
    priority:    float
    status:      str            # pending | active | complete | abandoned
    source:      str            # "human" or node name that generated it
    created_at:  str
    updated_at:  str
    parent_id:   Optional[str] = None
    depends_on:  list = field(default_factory=list)
    assigned_to: Optional[str] = None
    closes_gap:  Optional[str] = None  # belief_id of gap this goal closes, set by strategist


@dataclass
class Event:
    """
    Append-only log entry. Everything that happens gets recorded here.
    This is the collective's episodic memory.
    """
    id:         str
    event_type: str             # node_output | belief_formed | goal_added | consensus_reached
    agent:      str
    content:    str
    importance: float
    timestamp:  str
    goal_id:    Optional[str] = None
    tags:       list = field(default_factory=list)


@dataclass
class NodeRecord:
    """Registry entry for an active Legion node."""
    name:            str
    role_type:       str        # "procedural" or "evaluative"
    capabilities:    list
    last_active:     str
    tasks_completed: int = 0
    status:          str = "idle"   # "idle" | "busy" | "offline"
    current_goal_id: Optional[str] = None  # goal currently assigned to this node


# ── World Model ───────────────────────────────────────────────────────────────

class SharedWorldModel:
    """
    The Legion hivemind's shared persistent state.
    All nodes read from and write to a single instance of this class.

    Usage:
        wm = SharedWorldModel("data/world_model.json")
        await wm.load()

        await wm.add_event("skeptic", "node_output", "The plan has a flaw...", importance=1.0)
        await wm.add_belief("plan_is_flawed", "The merge step needs two pointers", confidence=0.9, source="skeptic")
        context = wm.retrieve_context("merge sort implementation", top_k=5)
    """

    def __init__(self, path: str = "data/world_model.json", decay: float = 0.01):
        self.path    = Path(path)
        self.decay   = decay
        self._lock   = asyncio.Lock()

        self.beliefs: dict[str, Belief]     = {}
        self.goals:   dict[str, Goal]       = {}
        self.events:  list[Event]           = []
        self.nodes:   dict[str, NodeRecord] = {}

        self._event_counter = 0

    # ── Persistence ───────────────────────────────────────────────────────────

    async def load(self) -> None:
        if not self.path.exists():
            self.path.parent.mkdir(parents=True, exist_ok=True)
            await self.save()
            return

        async with self._lock:
            with open(self.path) as f:
                data = json.load(f)

            # setdefault guards: fields added after initial serialization won't
            # exist in older JSON records. Each line ensures the key is present
            # before **v unpacking so dataclass construction never receives an
            # unexpected-keyword or missing-argument error.

            beliefs_raw = data.get("beliefs", {})
            for v in beliefs_raw.values():
                v.setdefault("tags", [])
                v.setdefault("evidence", [])
            self.beliefs = {k: Belief(**v) for k, v in beliefs_raw.items()}

            goals_raw = data.get("goals", {})
            for v in goals_raw.values():
                v.setdefault("parent_id", None)
                v.setdefault("depends_on", [])
                v.setdefault("assigned_to", None)
                v.setdefault("closes_gap", None)
            self.goals = {k: Goal(**v) for k, v in goals_raw.items()}

            nodes_raw = data.get("nodes", {})
            for v in nodes_raw.values():
                v.setdefault("tasks_completed", 0)
                v.setdefault("status", "idle")
                v.setdefault("current_goal_id", None)
            self.nodes = {k: NodeRecord(**v) for k, v in nodes_raw.items()}

            events_raw = data.get("events", [])
            for e in events_raw:
                e.setdefault("goal_id", None)
                e.setdefault("tags", [])
            self.events = [Event(**e) for e in events_raw]

            self._event_counter = len(self.events)

    async def _save_unlocked(self) -> None:
        """
        Write current state to disk WITHOUT acquiring the lock.
        Caller must already hold self._lock.
        Used internally by write methods that hold the lock to avoid
        nested lock acquisition (asyncio locks are not reentrant).
        """
        data = {
            "beliefs": {k: asdict(v) for k, v in self.beliefs.items()},
            "goals":   {k: asdict(v) for k, v in self.goals.items()},
            "nodes":   {k: asdict(v) for k, v in self.nodes.items()},
            "events":  [asdict(e) for e in self.events],
            "meta": {
                "last_saved":   datetime.now().isoformat(),
                "event_count":  len(self.events),
                "belief_count": len(self.beliefs),
                "goal_count":   len(self.goals),
            }
        }
        with open(self.path, "w") as f:
            json.dump(data, f, indent=2)

    async def save(self) -> None:
        """
        Write current state to disk, acquiring the lock.
        Use for external callers that do not hold the lock.
        Internal write methods use _save_unlocked() instead.
        """
        async with self._lock:
            await self._save_unlocked()

    # ── Write operations ──────────────────────────────────────────────────────

    async def add_event(
        self,
        agent:      str,
        event_type: str,
        content:    str,
        importance: float = 0.5,
        goal_id:    Optional[str] = None,
        tags:       list = None,
    ) -> Event:
        """Record anything that happens. Primary write operation for nodes."""
        self._event_counter += 1
        event = Event(
            id=f"evt_{self._event_counter:06d}",
            event_type=event_type,
            agent=agent,
            content=content,
            importance=importance,
            timestamp=datetime.now().isoformat(),
            goal_id=goal_id,
            tags=tags or [],
        )
        async with self._lock:
            self.events.append(event)
            await self._save_unlocked()
        return event

    async def add_belief(
        self,
        belief_id:  str,
        content:    str,
        confidence: float,
        source:     str,
        tags:       list = None,
        evidence:   list = None,
    ) -> Belief:
        """
        Commit a belief. Called by ConsensusEngine after nodes agree.
        Updates existing belief if belief_id already exists.
        """
        now = datetime.now().isoformat()
        async with self._lock:
            if belief_id in self.beliefs:
                existing = self.beliefs[belief_id]
                existing.content    = content
                existing.confidence = confidence
                existing.updated_at = now
                if evidence:
                    existing.evidence.extend(evidence)
                belief = existing
            else:
                belief = Belief(
                    id=belief_id, content=content, confidence=confidence,
                    source=source, created_at=now, updated_at=now,
                    tags=tags or [], evidence=evidence or [],
                )
            self.beliefs[belief_id] = belief
            await self._save_unlocked()
        return belief

    async def delete_belief(self, belief_id: str) -> bool:
        """
        Remove a belief by ID. Returns True if deleted, False if not found.

        Primary use case: cleaning up internal tracking beliefs (e.g. retry_count_{goal_id})
        after a goal is resolved or abandoned, so they don't accumulate across long runs.
        Not called on gap_ beliefs — use resolve_gap() for those.
        """
        async with self._lock:
            if belief_id not in self.beliefs:
                return False
            del self.beliefs[belief_id]
            await self._save_unlocked()
        return True

    async def add_goal(
        self,
        description: str,
        priority:    float = 0.5,
        source:      str   = "human",
        parent_id:   Optional[str] = None,
        depends_on:  list  = None,
        closes_gap:  Optional[str] = None,
    ) -> Goal:
        """
        Add a goal. Called by human OR by Planner node (self-direction).
        Self-generated goals are the key property that makes Legion alive.

        closes_gap: belief_id of a gap belief this goal is intended to close.
                    Set by the strategist. Consensus reads it on commit and
                    marks the gap belief as resolved.
        """
        async with self._lock:
            # ID computed inside the lock so len(self.goals) is stable.
            # Outside-lock computation causes a race: two concurrent callers
            # can both read the same len before either write, land on the same
            # ID within the same second, and the second write silently clobbers
            # the first (asyncio doesn't protect against this at the read site).
            goal_id = f"goal_{len(self.goals):04d}_{datetime.now().strftime('%H%M%S')}"
            now = datetime.now().isoformat()
            goal = Goal(
                id=goal_id, description=description, priority=priority,
                status="pending", source=source, created_at=now, updated_at=now,
                parent_id=parent_id, depends_on=depends_on or [],
                closes_gap=closes_gap,
            )
            self.goals[goal_id] = goal
            await self._save_unlocked()
        return goal

    async def update_goal_status(
        self,
        goal_id:          str,
        status:           str,
        assigned_to:      Optional[str] = None,
        clear_assignment: bool = False,
    ) -> None:
        """
        Update goal status and optionally reassign or clear assignment.

        assigned_to=None, clear_assignment=False (default):
            Leave assigned_to unchanged.
        assigned_to="node_name":
            Set assignee explicitly.
        clear_assignment=True:
            Set assigned_to=None, returning the goal to the unassigned pool.
        """
        if goal_id not in self.goals:
            return
        async with self._lock:
            goal = self.goals[goal_id]
            goal.status     = status
            goal.updated_at = datetime.now().isoformat()
            if clear_assignment:
                goal.assigned_to = None
            elif assigned_to is not None:
                goal.assigned_to = assigned_to
            await self._save_unlocked()

    async def register_node(self, name: str, role_type: str, capabilities: list) -> None:
        now = datetime.now().isoformat()
        async with self._lock:
            if name in self.nodes:
                self.nodes[name].last_active = now
            else:
                self.nodes[name] = NodeRecord(
                    name=name, role_type=role_type,
                    capabilities=capabilities, last_active=now,
                )
            await self._save_unlocked()

    # ── Retrieval ─────────────────────────────────────────────────────────────

    def retrieve_context(self, query: str, top_k: int = 5, agent_filter: str = None) -> list[Event]:
        """
        Retrieve relevant events using recency + importance + relevance.

        agent_filter: restrict to one node's outputs — enables self-retrieval,
                      the mechanism behind emergent self-correction (JARVIS paper).
        """
        candidates = self.events
        if agent_filter:
            candidates = [e for e in self.events if e.agent == agent_filter]
        if not candidates:
            return []

        query_words = set(re.findall(r'\b\w+\b', query.lower()))
        now = datetime.now()
        n   = len(candidates)

        hours = np.array([
            (now - datetime.fromisoformat(e.timestamp)).total_seconds() / 3600
            for e in candidates
        ])
        recency    = np.exp(-self.decay * hours)

        imp        = np.array([e.importance for e in candidates])
        max_imp    = imp.max()
        importance = imp / max_imp if max_imp > 0 else np.zeros(n)

        raw_rel   = np.array([
            len(set(re.findall(r'\b\w+\b', e.content.lower())) & query_words)
            for e in candidates
        ])
        max_rel   = raw_rel.max()
        relevance = raw_rel / max_rel if max_rel > 0 else np.zeros(n)

        combined = recency + importance + relevance
        top_idx  = combined.argsort()[::-1][:top_k]
        return [candidates[i] for i in top_idx]

    def format_context_for_prompt(self, query: str, top_k: int = 5, agent_filter: str = None) -> str:
        """Ready-to-inject context string for node prompts."""
        events = self.retrieve_context(query, top_k, agent_filter)
        if not events:
            return "(no relevant collective memory)"
        lines = []
        for e in events:
            tag_str = f" [{','.join(e.tags)}]" if e.tags else ""
            lines.append(f"[{e.agent} | {e.event_type}{tag_str}]\n{e.content}")
        return "\n\n".join(lines)

    def get_active_beliefs(self, min_confidence: float = 0.5) -> list[Belief]:
        """The collective's current committed worldview."""
        return [b for b in self.beliefs.values() if b.confidence >= min_confidence]

    def get_open_gaps(self) -> list[Belief]:
        """
        Return gap beliefs that have not yet been resolved.
        Used by the strategist to generate closure goals.
        A gap is open if its id starts with 'gap_' and 'resolved' is not in its tags.
        """
        return [
            b for b in self.beliefs.values()
            if b.id.startswith("gap_") and "resolved" not in b.tags
        ]

    async def resolve_gap(self, gap_belief_id: str) -> None:
        """
        Mark a gap belief as resolved by appending 'resolved' to its tags.
        Called by ConsensusEngine when a goal with closes_gap set is committed.
        No-op if the belief doesn't exist or is already resolved.
        """
        async with self._lock:
            belief = self.beliefs.get(gap_belief_id)
            if belief is None or "resolved" in belief.tags:
                return
            belief.tags.append("resolved")
            belief.updated_at = datetime.now().isoformat()
            await self._save_unlocked()

    def get_pending_goals(self) -> list[Goal]:
        """Goals ready to work on, sorted by priority. Used by GoalStack."""
        ready = [
            g for g in self.goals.values()
            if g.status == "pending"
            and all(
                self.goals.get(dep, Goal("","","",0,"complete","","","")).status == "complete"
                for dep in g.depends_on
            )
        ]
        return sorted(ready, key=lambda g: g.priority, reverse=True)

    # ── Introspection ─────────────────────────────────────────────────────────

    def status(self) -> dict:
        return {
            "beliefs":       len(self.beliefs),
            "goals_total":   len(self.goals),
            "goals_pending": len([g for g in self.goals.values() if g.status == "pending"]),
            "goals_active":  len([g for g in self.goals.values() if g.status == "active"]),
            "goals_done":    len([g for g in self.goals.values() if g.status == "complete"]),
            "events":        len(self.events),
            "nodes_online":  len(self.nodes),
        }

    def __repr__(self) -> str:
        s = self.status()
        return (
            f"SharedWorldModel("
            f"beliefs={s['beliefs']}, "
            f"goals={s['goals_pending']} pending / {s['goals_done']} done, "
            f"events={s['events']}, "
            f"nodes={s['nodes_online']})"
        )